// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDEHjQ880J9CubKavi99Mjvf4bzNhwq4',
    appId: '1:684957892455:web:4ee6d1102ebf4d91e779c2',
    messagingSenderId: '684957892455',
    projectId: 'testapp-9df38',
    authDomain: 'testapp-9df38.firebaseapp.com',
    storageBucket: 'testapp-9df38.appspot.com',
    measurementId: 'G-50Y2QGF8FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvuo2TQ7WBzKxCEZS1PFf0-A6ssaubYU',
    appId: '1:684957892455:android:b88bdb42e4db946ce779c2',
    messagingSenderId: '684957892455',
    projectId: 'testapp-9df38',
    storageBucket: 'testapp-9df38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcSwav9yc2xDUwqNk2A8xB_GnS1w9170',
    appId: '1:684957892455:ios:149f2d9299dc6107e779c2',
    messagingSenderId: '684957892455',
    projectId: 'testapp-9df38',
    storageBucket: 'testapp-9df38.appspot.com',
    androidClientId: '684957892455-25f59kd3mbrvrd4bfknuduslo788oca3.apps.googleusercontent.com',
    iosClientId: '684957892455-1av0bvn671rrs5utqgoit8kbk5q01ta2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcSwav9yc2xDUwqNk2A8xB_GnS1w9170',
    appId: '1:684957892455:ios:149f2d9299dc6107e779c2',
    messagingSenderId: '684957892455',
    projectId: 'testapp-9df38',
    storageBucket: 'testapp-9df38.appspot.com',
    androidClientId: '684957892455-25f59kd3mbrvrd4bfknuduslo788oca3.apps.googleusercontent.com',
    iosClientId: '684957892455-1av0bvn671rrs5utqgoit8kbk5q01ta2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNDEHjQ880J9CubKavi99Mjvf4bzNhwq4',
    appId: '1:684957892455:web:14ae82d5e4b7122ae779c2',
    messagingSenderId: '684957892455',
    projectId: 'testapp-9df38',
    authDomain: 'testapp-9df38.firebaseapp.com',
    storageBucket: 'testapp-9df38.appspot.com',
    measurementId: 'G-5MZ7EX7B17',
  );

}